
#fabric:
caOrgCert: |
   -----BEGIN CERTIFICATE-----
   MIICFzCCAb2gAwIBAgIUG+uQ6PljgHTsc+8fntfc0BFu8lUwCgYIKoZIzj0EAwIw
   ZzELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
   EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRgwFgYDVQQDEw9jYS5vcmdh
   cGVlci5jb20wIBcNMjEwMzExMDEzOTAwWhgPMjEyMTAzMTIwMTM5MDBaMGcxCzAJ
   BgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEUMBIGA1UEChMLSHlw
   ZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzEYMBYGA1UEAxMPY2Eub3JnYXBlZXIu
   Y29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJH8VT5R9SF1z0fiF5UK40P6u
   Td1U8ZN1r/gcWDdURj9zIx8V9OEpIISCVmKx+L8LkpHiQNlZg6NjSW2hbIekzqNF
   MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
   FEEgRrMkjxNsgX4eyvOWypTw8kh7MAoGCCqGSM49BAMCA0gAMEUCIQDYitqlVZAt
   FD8N00hLZpb6SN05GSSloziZ9Fr2quqF2wIgJoIHZdSX61W5cauUjlhy6uXaAF7D
   5odhuJ+7aVP27os=
   -----END CERTIFICATE-----
caURL: http://172.30.1.7:7054
caId: admin
caPw: adminpw
mspId: apeerMSP
channelName: test1-channel
chaincodeName: helloworld-cc